# Generated by Django 4.1.7 on 2023-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='imgs')),
            ],
        ),
    ]
