# Generated by Django 4.1.7 on 2023-03-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_image', models.ImageField(upload_to='imgs')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
