# Generated by Django 4.1.7 on 2023-03-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimages', '0002_userdetails_delete_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='description',
        ),
    ]
